[[opener.edit]]
run = 'zyn "$@"'
block = false
desc = "Edit with Zyn"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
